### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by flower-alone** [z4r4tu5tr4/PyRarCrack#4]
C:\Users\Flower\Desktop>python pyrarcrack.py --start 10 --stop 10 --file example_path.rar --alphabet 1234567890

`Traceback (most recent call last):
  File "pyrarcrack.py", line 90, in <module>
    stderr=PIPE,
  File "C:\Users\Flower\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Flower\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Yes, I made sure the rar exists, if it doesn't it gives you a different error.

**Comment by Bodok4tor** [comment]
Hi i had the same issue. I fixed this issue with simply copy the script and the rar in the winrar folder. For me it works.

It should look like this: C:\Program Files\WinRAR>python pyrarcrack.py --start 10 --stop 10 --file example_path.rar --alphabet 1234567890
